services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - monitoring
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/var/loki

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "9080:9080"
    networks:
      - monitoring
    restart: always
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./app.log:/var/log/app.log
    command:
      - -config.file=/etc/promtail/promtail-config.yaml

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: